-- Create the database if it doesn't exist
DROP DATABASE IF EXISTS reservation_management;
CREATE DATABASE IF NOT EXISTS reservation_management;
USE reservation_management;

-- Create Item Table
CREATE TABLE IF NOT EXISTS Items (

    uuid CHAR(36) PRIMARY KEY NOT NULL DEFAULT (UUID()), -- Unique identifier for each item (UUID)
        -- UUID being randomly generated by the UUID() function

    item_name VARCHAR(255) NOT NULL,  -- Name of the item
    time_of_addition TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Time item was added
    quantity INT NOT NULL,  -- Current quantity of the item
    reserved_status BOOLEAN DEFAULT FALSE,  -- Whether the item is reserved
    reservation_duration ENUM('1 day', '1 month') DEFAULT '1 day',  -- Duration of the reservation
    reservation_time TIMESTAMP NULL,  -- Time when the item was reserved
    location VARCHAR(255) NULL,  -- Warehouse or location of the item
    warehouse_name VARCHAR(255) NULL,  -- Name of the warehouse
    room_location VARCHAR(255) NULL,  -- Room or specific location within the warehouse
    price DECIMAL(10,2) NOT NULL,  -- Price of the item
    next_restock TIMESTAMP NULL  -- Next restock date and time
);

-- Create Inventory Table
CREATE TABLE IF NOT EXISTS Inventories (
    inventory_id CHAR(36) PRIMARY KEY,  -- UUID for the inventory
    inventory_name VARCHAR(255) NOT NULL,  -- Name of the inventory
    user_key CHAR(36) NOT NULL  -- User's unique key (foreign key to users)
);

-- Create Inventory Items Junction Table (for Inventory to Item relationship)
CREATE TABLE IF NOT EXISTS Inventory_Items (
    inventory_id CHAR(36),  -- FK to Inventory
    item_uuid CHAR(36),  -- FK to Item
    PRIMARY KEY (inventory_id, item_uuid),
    FOREIGN KEY (inventory_id) REFERENCES Inventories(inventory_id) ON DELETE CASCADE,

    -- TODO: Figure out how to refer to multiple items within an inventory
    FOREIGN KEY (item_uuid) REFERENCES Items(uuid) ON DELETE CASCADE
);

-- Create Users Table
CREATE TABLE IF NOT EXISTS Users (
    user_key CHAR(36) PRIMARY KEY,  -- Unique user key (UUID)
    username VARCHAR(255) NOT NULL,  -- Name of the user
    role ENUM('Admin', 'Secretary', 'User') NOT NULL DEFAULT 'User',  -- User roles
    last_access TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Time of last access
    item_action VARCHAR(255),  -- Item created/modified/deleted by the user
    inventory_access CHAR(36),  -- FK to inventory user has access to
    FOREIGN KEY (inventory_access) REFERENCES Inventories(inventory_id) ON DELETE SET NULL
);

-- Here we add the foreign key to connect the user to the inventories they have access to
ALTER TABLE Inventories
ADD CONSTRAINT fk_user_inventory
    FOREIGN KEY (user_key)
    REFERENCES Users (user_key)
    ON DELETE CASCADE;

-- Sample insert for Users
INSERT INTO Users (user_key, username, role)
VALUES
('u1234567-abcd-4d5e-9999-abcdef012345', 'admin1', 'Admin'),
('u89f6789-abcd-4d5e-8888-abcdef876543', 'secretary1', 'Secretary');


-- Sample inserts for Items
INSERT INTO Items (uuid, item_name, quantity, reserved_status, price)
VALUES
('c56a4180-65aa-42ec-a945-5fd21dec0538', 'Laptop', 50, FALSE, 1200.00),
('a123b789-123b-48ec-923f-d9b8f06ba7aa', 'Mouse', 200, TRUE, 25.99);

-- Sample inserts for Inventories
INSERT INTO Inventories (inventory_id, inventory_name, user_key)
VALUES
('bf456378-a8b3-40b6-b1a1-654bc9de5f02', 'Electronics Inventory', 'u1234567-abcd-4d5e-9999-abcdef012345'),
('bd123478-12ab-45f6-abc8-4456ac987654', 'Office Supplies Inventory', 'u89f6789-abcd-4d5e-8888-abcdef876543');

-- Sample insert into Inventory_Items (linking inventories to items)
INSERT INTO Inventory_Items (inventory_id, item_uuid)
VALUES
('bf456378-a8b3-40b6-b1a1-654bc9de5f02', 'c56a4180-65aa-42ec-a945-5fd21dec0538'),
('bd123478-12ab-45f6-abc8-4456ac987654', 'a123b789-123b-48ec-923f-d9b8f06ba7aa');